server:
  port: 8082

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

grpc:
  port: 8083

integration:
  registry:
    baseUrl: http://localhost:8080

logging:
  level:
    root: INFO
    com.github.vkremianskii.pits: DEBUG
