server:
  port: 8081

spring:
  flyway:
    url: jdbc:postgresql://localhost:5432/registry
    user: registry
    password: registry
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/registry
    username: registry
    password: registry
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
