services:
  db:
    image: postgres:14.3
    environment:
      POSTGRES_DB: pits
      POSTGRES_USER: pits
      POSTGRES_PASSWORD: pits
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  adminer:
    image: adminer:4.8.1
    ports:
      - "8090:8080"
  rabbitmq:
    image: rabbitmq:3.10.2-management
    ports:
      - "5672:5672"
      - "15672:15672"
  registry:
    image: pits/registry
    build:
      context: ../
      dockerfile: ./docker/registry.Dockerfile
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8080:8080"
  processes:
    image: pits/processes
    build:
      context: ../
      dockerfile: ./docker/processes.Dockerfile
    depends_on:
      - db
      - rabbitmq
      - registry
    ports:
      - "8081:8081"
  communicator:
    image: pits/communicator
    build:
      context: ../
      dockerfile: ./docker/communicator.Dockerfile
    depends_on:
      - rabbitmq
      - registry
    ports:
      - "8082:8082"
      - "8083:8083"
