services:
  # Backend
  auth:
    image: pits/auth
    build:
      context: ../
      dockerfile: ./docker/auth.Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
  registry:
    image: pits/registry
    build:
      context: ../
      dockerfile: ./docker/registry.Dockerfile
    depends_on:
      - db
      - rabbitmq
      - auth
    ports:
      - "8081:8081"
  processes:
    image: pits/processes
    build:
      context: ../
      dockerfile: ./docker/processes.Dockerfile
    depends_on:
      - db
      - rabbitmq
      - auth
      - registry
    ports:
      - "8082:8082"
  communicator:
    image: pits/communicator
    build:
      context: ../
      dockerfile: ./docker/communicator.Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "8083:8083"
      - "8084:8084"

  # Infra
  db:
    image: postgres:14.3
    environment:
      POSTGRES_DB: pits
      POSTGRES_USER: pits
      POSTGRES_PASSWORD: pits
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  adminer:
    image: adminer:4.8.1
    ports:
      - "8090:8080"
  rabbitmq:
    image: rabbitmq:3.10.2-management
    ports:
      - "5672:5672"
      - "15672:15672"

  # ELK
  elasticsearch:
    image: elasticsearch:${ELK_VERSION}
    environment:
      discovery.type: single-node
    volumes:
      - ./elasticsearch/jvm_mem_512m:/usr/share/elasticsearch/config/jvm.options.d/jvm_mem_512m
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - elastic
    ports:
      - "9200:9200"
      - "9300:9300"
    mem_limit: 1g
  logstash:
    image: logstash:${ELK_VERSION}
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/jvm.options:/usr/share/logstash/config/jvm.options
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - elastic
    ports:
      - "12201:12201/udp"
    mem_limit: 1g
  kibana:
    image: kibana:${ELK_VERSION}
    depends_on:
      - elasticsearch
    networks:
      - elastic
    ports:
      - "5601:5601"
    mem_limit: 512m

networks:
  elastic:
    driver: bridge
