services:
  db:
    image: postgres:14.3
    environment:
      POSTGRES_DB: pits
      POSTGRES_USER: pits
      POSTGRES_PASSWORD: pits
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  adminer:
    image: adminer:4.8.1
    ports:
      - "8090:8080"
  rabbitmq:
    image: rabbitmq:3.10.2-management
    ports:
      - "5672:5672"
      - "15672:15672"
