services:
  # Backend
  auth:
    image: pits/auth
    build:
      context: ../
      dockerfile: ./docker/auth.Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
  registry:
    image: pits/registry
    build:
      context: ../
      dockerfile: ./docker/registry.Dockerfile
    depends_on:
      - db
      - rabbitmq
      - auth
    ports:
      - "8081:8081"
  processes:
    image: pits/processes
    build:
      context: ../
      dockerfile: ./docker/processes.Dockerfile
    depends_on:
      - db
      - rabbitmq
      - auth
      - registry
    ports:
      - "8082:8082"
  communicator:
    image: pits/communicator
    build:
      context: ../
      dockerfile: ./docker/communicator.Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "8083:8083"
      - "8084:8084"

  # Infra
  db:
    image: postgres:14.3
    environment:
      POSTGRES_DB: pits
      POSTGRES_USER: pits
      POSTGRES_PASSWORD: pits
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  adminer:
    image: adminer:4.8.1
    ports:
      - "8090:8080"
  rabbitmq:
    image: rabbitmq:3.10.2-management
    ports:
      - "5672:5672"
      - "15672:15672"
  mongo:
    image: mongo:5.0.8
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: pits
    volumes:
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express:0.54.0
    ports:
      - "8091:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017
