server:
  port: 8081

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

grpc:
  port: 8082

integration:
  registry:
    port: 8080

logging:
  level:
    root: INFO
