server:
  port: 8080

spring:
  application:
    name: auth
  flyway:
    url: jdbc:postgresql://localhost:5432/auth
    user: auth
    password: auth
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/auth
    username: auth
    password: auth
