server:
  port: 8082

spring:
  flyway:
    url: jdbc:postgresql://localhost:5432/processes
    user: processes
    password: processes
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/processes
    username: processes
    password: processes
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

integration:
  auth:
    baseUrl: http://localhost:8080
  registry:
    baseUrl: http://localhost:8081

jobs:
  haul-cycle:
    cron: "*/15 * * * * *"
